services:
  postgres:
    container_name: postgres_database
    build:
      context: .
      dockerfile: Dockerfilepostgress
    ports:
      - ${POSTGRES_PORT_DEV}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
      POSTGRES_DB: ${POSTGRES_DB_DEV}
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - database_network

  mongo:
    image: mongo:7
    container_name: mongo-standalone
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_DEV}
    volumes:
      - mongo_data:/data/db
    networks:
      - database_network

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   # Neo4j Browser (GUI)
      - "7687:7687"   # Bolt protocol (driver connects here)
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME_DEV}/${NEO4J_PASSWORD_DEV}
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "${NEO4J_USERNAME_DEV}", "-p", "${NEO4J_PASSWORD_DEV}", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - database_network

  neo4j-init:
    image: neo4j:5
    container_name: neo4j_init
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./database/neo4j/cyphers/constraints-and-indexes.cypher:/init/constraints-and-indexes.cypher:ro
    environment:
      NEO4J_USERNAME: ${NEO4J_USERNAME_DEV}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD_DEV}
    networks:
      - database_network
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        echo "Applying Neo4j constraints and indexes..."
        cypher-shell -a bolt://neo4j:7687 -u $$NEO4J_USERNAME -p $$NEO4J_PASSWORD -f /init/constraints-and-indexes.cypher
        if [ $$? -eq 0 ]; then
          echo "Constraints and indexes applied successfully."
        else
          echo "Failed to apply constraints and indexes."
          exit 1
        fi
    restart: "no"

  

volumes:
  database_volume:
    name: ${DB_VOLUME_DEV}
  mongo_data:
  neo4j_data:

networks:
  database_network:
    name: database_network