// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env.DATABASE_URL//["DATABASE_URL"];

if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is required. Set it in your .env file located at /database/.env");
}

export default defineConfig({
  schema: "./database/prisma/schema.prisma",
  migrations: {
    path: "./database/prisma/migrations",
    seed: "tsx ./database/prisma/seed.ts"
  },
  datasource: {
    url: databaseUrl,
  },
});
